### ISSUE TITLE
学习macOS开发的路线 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#40]
https://www.sunyazhou.com/2017/01/13/Learning-macOS-development-shortcut/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by neo080** [comment]
你好，我正在学习mac os x开发，看了你的《macOS上模拟发送键盘事件》，有一个小问题想请教一下，我的系统是10.14.2，用你的代码运行第一次的时候系统会弹出提示，我在系统编好设置的隐私里允许了控制电脑，代码也运行成功了，但第二次跑的时候就没任何反应。是不是还有哪里没设置好？网上的资料太少了，我也是一个链接一个链接的最后才找到这里。不知道能不能麻烦你一下，非常感谢

**Comment by sunyazhou13** [comment]
没遇到过这种情况，理论上授权一次就行了，查查相关资料google看下吧




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 16:47，neo080 写道：

你好，我正在学习mac os x开发，看了你的《macOS上模拟发送键盘事件》，有一个小问题想请教一下，我的系统是10.14.2，用你的代码运行第一次的时候系统会弹出提示，我在系统编好设置的隐私里允许了控制电脑，代码也运行成功了，但第二次跑的时候就没任何反应。是不是还有哪里没设置好？网上的资料太少了，我也是一个链接一个链接的最后才找到这里。不知道能不能麻烦你一下，非常感谢

**Comment by neo080** [comment]
好的，没想到能这么快回复，感谢了。我再找找其它的资料吧

**Comment by sunyazhou13** [comment]
不可以  很久没写macOS了  




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 16:55，neo080 写道：

好的，没想到能这么快回复，感谢了。我再找找其它的资料吧

**Comment by sunyazhou13** [comment]
没关系




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 16:56，東引甌越 写道：
不可以  很久没写macOS了  




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 16:55，neo080 写道：

好的，没想到能这么快回复，感谢了。我再找找其它的资料吧

**Comment by neo080** [comment]
感觉mac开发的资料确实不好找，不像linux那么多。mac用了几年以一直把它当linux用。我先看下你的《学习macOS开发的路线》推荐吧。

**Comment by sunyazhou13** [comment]
嗯这个是个冷门，没人研究，一般都做跨平台，很少写原生的应用不像国外，国内大环境不好




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 17:00，neo080 写道：

感觉mac开发的资料确实不好找，不像linux那么多。mac用了几年以一直把它当linux用。我先看下你的《学习macOS开发的路线》推荐吧。

**Comment by neo080** [comment]
嗯，我也主要是兴趣吧，其实模拟键盘鼠标有更好的办法，但是正好在学这块。用golang或者苹果自己的AppleScript都很容易实现，没想到用原生的oc这么写鼠标键盘事件这么麻烦，老谭的博客我也看了，关于全局键盘监听也是从他那学来的。

**Comment by sunyazhou13** [comment]
老谭那个博客写的不错多学习学习




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2019年01月19日 17:08，neo080 写道：

嗯，我也主要是兴趣吧，其实模拟键盘鼠标有更好的办法，但是正好在学这块。用golang或者苹果自己的AppleScript都很容易实现，没想到用原生的oc这么写鼠标键盘事件这么麻烦，老谭的博客我也看了，关于全局键盘监听也是从他那学来的。

**Comment by neo080** [comment]
是啊，只是最后一篇是2017-09-24，可能太忙了又或者换网址了，我没有找到更新文章。
