### ISSUE TITLE
iOS抖音的转场动画 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#42]
https://www.sunyazhou.com/2018/12/21/20181221AwemeTransition/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by Wutaotao692732757** [comment]
不错

**Comment by HanFei0813** [comment]
播放列表不能及时dealloc

**Comment by sunyazhou13** [comment]
check一下performselector




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2020年06月21日 12:05，HanFeizi 写道：

播放列表不能及时dealloc
