### ISSUE TITLE
理解UIView的绘制 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#46]
https://www.sunyazhou.com/2017/10/16/20171016UIView-Rendering/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by xxycode** [comment]
25fps不卡一般是针对视频  因为视频有动态模糊 所以会不卡  但是如果APP只有25fps还是会卡的

**Comment by sunyazhou13** [comment]
> @xxycode
> 25fps不卡一般是针对视频  因为视频有动态模糊 所以会不卡  但是如果APP只有25fps还是会卡的

没错 这里不严谨 见笑 见笑 马上改正  确实 手机屏幕的刷新率 基本 60Hz以上才算得上比较流畅 当然 25FPS针对视频 是因为视频中有有 i  p  b 帧  能经过关键帧和双向预测以及单向预测帧读取上下帧得信息 不用重新 绘制  因为 GPU的索引  可以节省很多绘制资源
