### ISSUE TITLE
Windows装机教程 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#58]
https://www.sunyazhou.com/2019/04/24/20190424WindowsResources/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by yizibi** [comment]
厉害，终于有了win10的教程，我有一个win 7的启动U盘，win10没有的，刚看到开始，技术员那个资源，下意识找了 系统资源书签itellyou，真是个好资源网站，👍

**Comment by sunyazhou13** [comment]
> @yizibi
> 厉害，终于有了win10的教程，我有一个win 7的启动U盘，win10没有的，刚看到开始，技术员那个资源，下意识找了 系统资源书签itellyou，真是个好资源网站，👍

每次都因为 找不到 纯净的资源而闹心 必须整理一份留着备用
