### ISSUE TITLE
Cleaner For Xcode编译 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#60]
https://www.sunyazhou.com/2019/05/17/20190517CleanerForXcodeBuild/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by yizibi** [comment]
真的不错，方便很多，以前都是找到对应的文件夹清理的，这个我可以转载不，会注明出处的

**Comment by sunyazhou13** [comment]
> @yizibi
> 真的不错，方便很多，以前都是找到对应的文件夹清理的，这个我可以转载不，会注明出处的

后来发现一个比这个还好的 腾讯出的 lemon 可以试试

**Comment by yizibi** [comment]
谢谢安利，我下载了，不错

**Comment by sunyazhou13** [comment]
> @yizibi
> 真的不错，方便很多，以前都是找到对应的文件夹清理的，这个我可以转载不，会注明出处的

可以

**Comment by niuxinghua** [comment]
楼主好人
