### ISSUE TITLE
呼吸动画 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#7]
https://www.sunyazhou.com/2018/09/29/20180929BreathAnimation/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by yizibi** [comment]
有点像心跳的动画,文中的具体需求,下面这句话:

> 每次放大同时需要背景还有一张图也方法 并且透明

中,`也方法`,还是也放大??:joy:   :joy:

**Comment by sunyazhou13** [comment]
> @yizibi
> 有点像心跳的动画,文中的具体需求,下面这句话:
> 
> > 每次放大同时需要背景还有一张图也方法 并且透明
> 
> 中,`也方法`,还是也放大??:joy:   :joy:

已修复 请刷新测试一下 感谢支持

**Comment by yizibi** [comment]
> > @yizibi
> > 有点像心跳的动画,文中的具体需求,下面这句话:
> > > 每次放大同时需要背景还有一张图也方法 并且透明
> > 
> > 
> > 中,`也方法`,还是也放大??😂   😂
> 
> 已修复 请刷新测试一下 感谢支持

好像你的网站挂掉了!!!
