### ISSUE TITLE
阿里、字节：一套高效的iOS面试题之我整理的答案 | 東引甌越

### ISSUE THREAD

**Issue by sunyazhou13** [sunyazhou13/gitment-comments#86]
https://www.sunyazhou.com/2020/07/06/20200721iOSinterviewAnswers/ 

 我是孙亚洲(@sunyazhou13),一名来自北国冰城的iOS开发者,走在成为圣贤的路上.

**Comment by yizibi** [comment]
runtime相关问题
关联属下？应该是属性吧？笔误，哈哈

**Comment by sunyazhou13** [comment]
马上改下





| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2020年08月31日 15:14，一之笔 写道：

runtime相关问题
关联属下？应该是属性吧？笔误，哈哈

**Comment by sunyazhou13** [comment]
再试试




| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2020年08月31日 15:14，東引甌越 写道：
马上改下





| |
孙亚洲
|
|
邮箱：sunyazhou13@163.com
|

签名由 网易邮箱大师 定制

在2020年08月31日 15:14，一之笔 写道：

runtime相关问题
关联属下？应该是属性吧？笔误，哈哈
